# test-workflow.yml
name: Simple Demo Workflow
on:
  push:
    branches:
      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Job 1 - Step 1"
      - name: Step 2
        run: echo "Job 1 - Step 2"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Step 1
        run: echo "Job 2 - Step 1 (runs after Job 1)"
      - name: Step 2 (Simulate Error)
        run: |
          echo "Job 2 - Step 2 will now fail..."
          exit 1   # <-- manual error here

  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - name: Step 1
        run: echo "Job 3 - Step 1 (runs after Job 1 & Job 2)"
      - name: Step 2
        run: echo "Job 3 - Step 2"
